# Generated by Django 2.2.13 on 2020-06-03 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptwo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
